pipeline {
    agent any
    environment {
        TARGET_DIR = 'devops_prueba/app'
        REPOSITORY = 'estevancastro98/devco'
        TAG = 'test-devco'
        IMAGE_NAME = "${env.REPOSITORY}:${env.TAG}-${BUILD_NUMBER}"
    }

    stages {
        stage('Configurar Entorno Python') {
            steps {
                script {
                    sh 'python3 -m venv venv'
                    sh './venv/bin/pip install --upgrade pip'
                    sh './venv/bin/pip install pytest flask'
                }
            }
        }

        stage('Pruebas Unitarias') {
            steps {
                script {
                    sh './venv/bin/pytest devops_prueba/app/test.py --junitxml=report.xml'
                }
            }
        }

        stage('Análisis de Código con SonarQube') {
            environment {
                scannerHome = tool 'SonarQubeScanner'
            }
            steps {
                dir("${WORKSPACE}") {
                    script {
                        withSonarQubeEnv('SonarQubeScanner') {
                            sh """
                            ${scannerHome}/bin/sonar-scanner \
                            -Dsonar.projectKey=your_project_key \
                            -Dsonar.projectName=your_project_name \
                            -Dsonar.projectVersion=1.0-SNAPSHOT \
                            -Dsonar.sources=devops_prueba/app \
                            -Dsonar.sourceEncoding=UTF-8
                            """
                        }
                    }
                }
            }
        }

        stage('Verificación de Quality Gate') {
            steps {
                timeout(time: 1, unit: 'HOURS') {
                    waitForQualityGate abortPipeline: true
                }
            }
        }

        stage('Construir Imagen Docker - Etiqueta del Número de Compilación') {
            steps {
                script {
                    sh "docker build -t ${env.IMAGE_NAME} ${WORKSPACE}/${env.TARGET_DIR}/"
                }
            }
        }

        stage('Escaneo de Vulnerabilidades con Trivy') {
            steps {
                script {
                    def trivyOutput = sh(script: "docker run --rm -v /var/run/docker.sock:/var/run/docker.sock -v $WORKSPACE:/root/.cache/ aquasec/trivy:latest -q image --severity CRITICAL --light ${env.IMAGE_NAME}", returnStdout: true).trim()
                    echo trivyOutput

                    if (trivyOutput.contains('will_not_fix')) {
                        echo "Se encontraron vulnerabilidades críticas sin corrección disponible. Subiendo la imagen."
                    } else {
                        error("Vulnerabilidades críticas con versiones de corrección encontradas en la imagen Docker. Aborting.")
                    }
                }
            }
        }

        stage('Subir Imagen Docker - Etiqueta del Número de Compilación') {
            steps {
                script {
                    docker.withRegistry('https://index.docker.io/v1/', 'docker-2') {
                        sh "docker push ${env.IMAGE_NAME}"
                    }
                }
            }
        }
    }

    post {
        always {
            junit 'report.xml'
        }
    }
}
